import { AiFillStar } from 'react-icons/ai'

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "140",
    price: 200,
    company: "Nike",
    color: "white",
    category: "sneakers",
    id: 1,
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "140",
    price: 200,
    company: "Nike",
    color: "red",
    category: "sneakers",
    id: 2,
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "140",
    price: 200,
    company: "Nike",
    color: "green",
    category: "sneakers",
    id: 3,
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(3 reviews)",
    prevPrice: "140",
    price: 200,
    company: "Nike",
    color: "black",
    category: "sneakers",
    id: 4
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(12 reviews)",
    prevPrice: "110",
    price: 200,
    company: "Vans",
    color: "green",
    category: "flats",
    id: 5
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "140",
    price: 150,
    company: "Adidas",
    color: "black",
    category: "flats",
    id: 6
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(13 reviews)",
    prevPrice: "140",
    price: 120,
    company: "Vans",
    color: "white",
    category: "flats",
    id: 7
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "178",
    price: 200,
    company: "Nike",
    color: "green",
    category: "sneakers",
    id: 8
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Adidas Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(128 reviews)",
    prevPrice: "119",
    price: 200,
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    id: 9
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "149",
    price: 150,
    company: "Puma",
    color: "green",
    category: "sneakers",
    id: 10
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(182 reviews)",
    prevPrice: "146",
    price: 150,
    company: "Puma",
    color: "red",
    category: "sneakers",
    id: 11
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(12 reviews)",
    prevPrice: "140",
    price: 150,
    company: "Puma",
    color: "black",
    category: "sneakers",
    id: 12
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "140",
    price: 150,
    company: "Puma",
    color: "white",
    category: "sneakers",
    id: 13
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(12 reviews)",
    prevPrice: "140",
    price: 150,
    company: "Puma",
    color: "black",
    category: "sneakers",
    id: 14
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "145",
    price: 100,
    company: "Puma",
    color: "green",
    category: "sneakers",
    id: 15
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "140",
    price: 100,
    company: "Vans",
    color: "red",
    category: "flats",
    id: 16
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(183 reviews)",
    prevPrice: "140",
    price: 100,
    company: "Vans",
    color: "white",
    category: "sandals",
    id: 17
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(23 reviews)",
    prevPrice: "187",
    price: 100,
    company: "Vans",
    color: "blue",
    category: "sandals",
    id: 18
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(19 reviews)",
    prevPrice: "144",
    price: 50,
    company: "Adidas",
    color: "black",
    category: "sandals",
    id: 19
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(113 reviews)",
    prevPrice: "140",
    price: 50,
    company: "Vans",
    color: "black",
    category: "heels",
    id: 20
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(723 reviews)",
    prevPrice: "132",
    price: 100,
    company: "puma",
    color: "black",
    category: "heels",
    id: 21
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(323 reviews)",
    prevPrice: "149",
    price: 150,
    company: "Adidas",
    color: "red",
    category: "heels",
    id: 22
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(183 reviews)",
    prevPrice: "190",
    price: 200,
    company: "Nike",
    color: "red",
    category: "sneakers",
    id: 23
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(103 reviews)",
    prevPrice: "187",
    price: 200,
    company: "Adidas",
    color: "black",
    category: "heels",
    id: 24
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "98",
    price: 50,
    company: "Adidas",
    color: "black",
    category: "heels",
    id: 25
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(153 reviews)",
    prevPrice: "109",
    price: 150,
    company: "Adidas",
    color: "white",
    category: "heels",
    id: 26
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(129 reviews)",
    prevPrice: "140",
    price: 118,
    company: "Adidas",
    color: "black",
    category: "heels",
    id: 27
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: 147,
    price: 128,
    company: "Adidas",
    color: "black",
    category: "flats",
    id: 28
  },
  //
  {
    id: 29,
    title: "Adidas React Infinity Run Flyknit",
    company: "Adidas",
    "gender": "MEN",
    "category": "RUNNING",
    "price": 160,
    prevPrice: 178,
    img: "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-665455a5-45de-40fb-945f-c1852b82400d/react-infinity-run-flyknit-mens-running-shoe-zX42Nc.jpg",
    slug: "Adidas-react-infinity-run-flyknit"
  },
{
    "id": 30,
    "title": "Adidas React Miler",
    "company": "Adidas",
    "gender": "MEN",
    "category": "RUNNING",
    "price": 130,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-5cc7de3b-2afc-49c2-a1e4-0508997d09e6/react-miler-mens-running-shoe-DgF6nr.jpg",
    "slug": "Adidas-react-miler"
  },
  {
    "id": 31,
    "title": "Adidas Air Zoom Pegasus 37",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "RUNNING",
    "price": 120,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-33b0a0a5-c171-46cc-ad20-04a768703e47/air-zoom-pegasus-37-womens-running-shoe-Jl0bDf.jpg",
    "slug": "Adidas-air-zoom-pegasus-37"
  },
  {
    "id": 32,
    "title": "Adidas Joyride Run Flyknit",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "RUNNING",
    "price": 180,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/99a7d3cb-e40c-4474-91c2-0f2e6d231fd2/joyride-run-flyknit-womens-running-shoe-HcfnJd.jpg",
    "slug": "Adidas-joyride-run-flyknit"
  },
  {
    "id": 33,
    "title": "Adidas Mercurial Vapor 13 Elite FG",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "FOOTBALL",
    "price": 250,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/9dda6202-e2ff-4711-9a09-0fcb7d90c164/mercurial-vapor-13-elite-fg-firm-ground-soccer-cleat-14MsF2.jpg",
    "slug": "Adidas-mercurial-vapor-13-elite-fg"
  },
 {
    "id": 34,
    "title": "Adidas Phantom Vision Elite Dynamic Fit FG",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "FOOTBALL",
    "price": 150,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/s1amp7uosrn0nqpsxeue/phantom-vision-elite-dynamic-fit-fg-firm-ground-soccer-cleat-19Kv1V.jpg",
    "slug": "Adidas-phantom-vision-elite-dynamic-fit-fg"
  },
{
    "id": 35,
    "title": "Adidas Phantom Venom Academy FG",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "FOOTBALL",
    "price": 80,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/whegph8z9ornhxklc8rp/phantom-venom-academy-fg-firm-ground-soccer-cleat-6JVNll.jpg",
    "slug": "Adidas-phantom-venom-academy-fg"
  },
 {
    "id": 36,
    "title": "Adidas Mercurial Vapor 13 Elite Tech Craft FG",
    "company": "Adidas",
    "gender": "MEN",
    "category": "FOOTBALL",
    "price": 145,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/vhbwnkor8sxt8qtecgia/mercurial-vapor-13-elite-tech-craft-fg-firm-ground-soccer-cleat-l38JPj.jpg",
    "slug": "Adidas-mercurial-vapor-13-elite-tech-craft-fg"
  },
{
    "id": 37,
    "title": "Adidas Mercurial Superfly 7 Pro MDS FG",
    "company": "Adidas",
    "gender": "MEN",
    "category": "FOOTBALL",
    "price": 137,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-a52a8aec-22dc-4982-961b-75c5f4c72805/mercurial-superfly-7-pro-mds-fg-firm-ground-soccer-cleat-mhcpdN.jpg",
    "slug": "Adidas-mercurial-superfly-7-pro-mds-fg"
  },
  {
    "id": 38,
    "title": "Adidas Air Force 1",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "CASUAL",
    "price": 90,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/178b2a46-3ee4-492b-882e-f71efdd53a36/air-force-1-big-kids-shoe-2zqp8D.jpg",
    "slug": "Adidas-air-force-1"
  },
  {
    "id": 39,
    "title": "Adidas Air Max 90",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "CASUAL",
    "price": 100,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/8439f823-86cf-4086-81d2-4f9ff9a66866/air-max-90-big-kids-shoe-1wzwJM.jpg",
    "slug": "Adidas-air-max-90"
  },
{
    "id": 40,
    "title": "Adidas Air Max 90 LTR",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "CASUAL",
    "price": 110,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-620aeb37-1b28-44b0-9b14-5572f8cbc948/air-max-90-ltr-big-kids-shoe-hdNLQ5.jpg",
    "slug": "Adidas-air-max-90-ltr"
  },
  {
    "id": 41,
    "title": "Adidas Joyride Dual Run",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "RUNNING",
    "price": 110,
    "is_in_inventory": false,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/33888130-0320-41a1-ba53-a026decd8aa2/joyride-dual-run-big-kids-running-shoe-1HDJF8.jpg",
    "slug": "Adidas-joyride-dual-run"
  },
{
    "id": 42,
    "title": "Adidas Renew Run",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "RUNNING",
    "price": 80,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://static.Adidas.com/a/images/c_limit,w_592,f_auto/t_product_v1/i1-73e54c0b-11a6-478b-9f90-bd97fcde872d/renew-run-big-kids-running-shoe-5Bpz93.jpg",
    "slug": "Adidas-renew-run"
  },
 {
    "id": 43,
    "title": "Bridgport Advice",
    "company": "HUSHPUPPIES",
    "gender": "MEN",
    "category": "FORMAL",
    "price": 30,
    "is_in_inventory": true,
    "items_left": 4,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/BRIDGPORT_ADVICE-BLACK_1_800x800.jpg?v=1576567903",
    "slug": "bridgport-advice"
  },
{
    "id": 44,
    "title": "Beck",
    "company": "HUSHPUPPIES",
    "gender": "MEN",
    "category": "FORMAL",
    "price": 80,
    "is_in_inventory": true,
    "items_left": 5,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Beck-Black_800x800.jpg",
    "slug": "beck"
  },
{
    "id": 45,
    "title": "Fester",
    "company": "HUSHPUPPIES",
    "gender": "MEN",
    "category": "FORMAL",
    "price": 70,
    "is_in_inventory": true,
    "items_left": 6,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/fester-Tan_800x800.jpg?v=1575537531",
    "slug": "fester"
  },
{
    "id": 46,
    "title": "Pixel",
    "company": "HUSHPUPPIES",
    "gender": "MEN",
    "category": "FORMAL",
    "price": 75,
    "is_in_inventory": true,
    "items_left": 7,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/PIXEL-TAN_800x800.jpg?v=1577420506",
    "slug": "pixel"
  },
{
    "id": 47,
    "title": "Austin",
    "company": "HUSHPUPPIES",
    "gender": "MEN",
    "category": "FORMAL",
    "price": 75,
    "is_in_inventory": true,
    "items_left": 2,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/Austin-Coffee_800x800.jpg?v=1574772988",
    "slug": "austin"
  },
{
    "id": 48,
    "title": "SS-HL-0135",
    "company": "HUSHPUPPIES",
    "gender": "WOMEN",
    "category": "FORMAL",
    "price": 30,
    "is_in_inventory": true,
    "items_left": 6,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009240000-11-SS-HL-0135-Black_800x800.jpg?v=1572264270",
    "slug": "ss-hl-0135"
  },
{
    "id": 49,
    "title": "SS-HL-0136",
    "company": "HUSHPUPPIES",
    "gender": "WOMEN",
    "category": "FORMAL",
    "price": 50,
    "is_in_inventory": true,
    "items_left": 4,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009250000-779-SS-HL-0136-Coffee_800x800.jpg?v=1571900372",
    "slug": "ss-hl-0136"
  },
{
    "id": 50,
    "title": "SS-HL-0128",
    "company": "HUSHPUPPIES",
    "gender": "WOMEN",
    "category": "FORMAL",
    "price": 35,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/000300242-484-SS-HL-0128-Blue_800x800.jpg?v=1583235174",
    "slug": "ss-hl-0128"
  },
{
    "id": 51,
    "title": "SS-MS-0075",
    "company": "HUSHPUPPIES",
    "gender": "WOMEN",
    "category": "CASUAL",
    "price": 25,
    "is_in_inventory": true,
    "items_left": 7,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/009170000-479-SS-MS-0075-Red_800x800.jpg?v=1570688687",
    "slug": "ss-ms-0075"
  },
 {
    "id": 52,
    "title": "SS-PM-0093",
    "company": "HUSHPUPPIES",
    "gender": "WOMEN",
    "category": "CASUAL",
    "price": 30,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://cdn.shopify.com/s/files/1/0016/0074/9623/products/SS-PM-0093_1_800x800.jpg?v=1570601253",
    "slug": "ss-pm-0093"
  },
{
    "id": 53,
    "title": "Nizza X Disney",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "CASUAL",
    "price": 55,
    "is_in_inventory": true,
    "items_left": 6,
    "img": "https://assets.Adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/ef901c7aeac042578eceab9d0159196c_9366/Nizza_x_Disney_Sport_Goofy_Shoes_White_FW0651_01_standard.jpg",
    "slug": "nizza-x-disney"
  },
{
    "id": 54,
    "title": "X_PLR",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "CASUAL",
    "price": 65,
    "is_in_inventory": true,
    "items_left": 5,
    "img": "https://assets.Adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/a36518227134495da766ab9d01772fa2_9366/X_PLR_Shoes_Red_FY9063_01_standard.jpg",
    "slug": "x_plr"
  },
{
    "id": 55,
    "title": "Stan Smith",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "CASUAL",
    "price": 55,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://assets.Adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/d0720712d81e42b1b30fa80800826447_9366/Stan_Smith_Shoes_White_M20607_M20607_01_standard.jpg",
    "slug": "stan-smith"
  },
{
    "id": 56,
    "title": "NMD_R1",
    "company": "Adidas",
    "gender": "KIDS",
    "category": "RUNNING",
    "price": 120,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://assets.Adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/99ca762cb9054caf82fbabc500fd146e_9366/NMD_R1_Shoes_Blue_FY9392_01_standard.jpg",
    "slug": "nmd_r1"
  },
{
    "id": 57,
    "title": "NMD_R1 Flash Red",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "CASUAL",
    "price": 140,
    "is_in_inventory": true,
    "items_left": 5,
    "img": "https://assets.Adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/90f85768e3894aeaab67aba0014a3379_9366/NMD_R1_Shoes_Red_FY9389_01_standard.jpg",
    "slug": "nmd_r1-flash-red"
  },
{
    "id": 58,
    "title": "Superstar",
    "company": "Adidas",
    "gender": "WOMEN",
    "category": "CASUAL",
    "price": 90,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://assets.Adidas.com/images/h_320,f_auto,q_auto:sensitive,fl_lossy/12365dbc7c424288b7cdab4900dc7099_9366/Superstar_Shoes_White_FW3553_FW3553_01_standard.jpg",
    "slug": "superstar"
  },
{
    "id": 59,
    "title": "Club C Revenge Mens",
    "company": "Reebok",
    "gender": "MEN",
    "category": "CASUAL",
    "price": 70,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/7599294868804d78a1b1ab6f01718a5e_9366/Club_C_Revenge_Men's_Shoes_White_FV9877_01_standard.jpg",
    "slug": "club-c-revenge-mens"
  },
{
    "id": 60,
    "title": "SK80-Low",
    "company": "Vans",
    "gender": "MEN",
    "category": "CASUAL",
    "price": 60,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://images.vans.com/is/image/Vans/UUK24I-HERO?$583x583$",
    "slug": "sk80-low"
  },
  {
    "id": 61,
    "title": "Michael Feburary SK8-Hi",
    "company": "Vans",
    "gender": "MEN",
    "category": "CASUAL",
    "price": 72,
    "is_in_inventory": true,
    "items_left": 3,
    "img": "https://images.vans.com/is/image/Vans/MV122M-HERO?$583x583$",
    "slug": "michael-feburary-sk8-hi"
  }
];

export default data;
